### ISSUE TITLE
Loginscreen is briefly shown when user is already logged in

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#201] opened 2018-06-20 12:07 UTC
### Problem
When I open Boxwise while my session is still valid, I briefly see the login screen and just when I attempt to fill in my details, it disappears and it forwards to the dashboard page

### Fix
Make sure that the app forwards to the dashboard before displaying the login form.

**Comment by bfirsh** [comment] 2018-06-20 12:15
dupe of #181

**Closed by bfirsh** 2018-06-20 12:15 UTC
Labels: TripAdvisor HackDay, type/bug
